name: 'Deploy to Firebase Hosting'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_ENV_CONFIG: ${{ secrets.APP_ENV_CONFIG }}
      APP_ENV_CONFIG_FILE_PATH: ${{ './lib/env_config.dart' }}

    steps:
      - uses: actions/checkout@v2

      - name: 'Configure flutter'
        uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: '2.2.2'

      - name: 'Decode lib/env_config.dart'
        run: echo "${{ env.APP_ENV_CONFIG }}" > "${{ env.APP_ENV_CONFIG_FILE_PATH }}"

      - name: 'Build flutter web'
        run: flutter build web

      - name: 'Deploy to firebase hosting'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_WEB_GRAPHQL }}'
          channelId: live
          projectId: flutter-web-graphql
